# 01. 넘파이

## 1. 라이브러리 불러오기

In [9]:
import numpy as np

## 2. 배열 만들기

In [14]:
# 1차원 만들기
arr1 = np.array([1,2,3,4,5])
# 2차원 만들기
arr2 = np.array([[1,2,3],[4,5,6]])
# 3차원 만들기
arr3 = np.array([[[1.,2.,3.]],
                 [[1.,2.,3.]]])

print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1. 2. 3.]]

 [[1. 2. 3.]]]


#### 1) 차원 확인

In [10]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


####  2) 형태(크기) 확인

In [11]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 3)
(2, 1, 3)


#### 3) 요소 자료형 확인

In [15]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
int32
float64


#### 4) 차원 변경

In [20]:
print(arr2.reshape(3,2))
print(arr2.reshape(2,-1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


#### 5) 인덱싱

In [57]:
arr = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

In [30]:
print(arr[0,1])
print(arr[0][1])
print(arr[[0,1]])
print(arr[:, [0, 2]])

2
2
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]
 [7 9]]


#### 6) 슬라이싱

In [34]:
print(arr[:,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(arr[1:3, 0:1])

[[4]
 [7]]


In [40]:
print(arr[:, 1])
print(arr[:, 1:2])

[2 5 8]
[[2]
 [5]
 [8]]


#### 7) 조건 조회

In [42]:
print(arr[arr> 7])

[8 9]


In [46]:
print((arr[(arr > 7) & (arr > 8)]))

[9]


#### 8) 배열 연산

In [47]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [48]:
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [50]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [51]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [53]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [54]:
print(x**y)
print(np.power(x,y))

[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]


In [61]:
print(np.sum(arr))
print(np.sum(arr, axis = 0))  # 열기준 집계
print(np.sum(arr, axis = 1))  # 행기준 집계

45
[12 15 18]
[ 6 15 24]


# 02. 판다스

In [2]:
import pandas as pd

In [3]:
dict = {'Name': ['Gildong', 'Sarang', 'Jiemae', 'Yeoin', 'James', 'Sen'],
        'Grade': [1, 3, 4, 2, 3, 4],
        'Score': [56000, 23000, 44000, 52000, 52000, 60000]}
df = pd.DataFrame(dict)
print(df)

      Name  Grade  Score
0  Gildong      1  56000
1   Sarang      3  23000
2   Jiemae      4  44000
3    Yeoin      2  52000
4    James      3  52000
5      Sen      4  60000


#### 1) 상위 데이터 확인

In [70]:
df.head()

Name  Grade  Score
0  Gildong      1  56000
1   Sarang      3  23000
2   Jiemae      4  44000
3    Yeoin      2  52000
4    James      3  55000

#### 2) 하위 데이터 확인

In [71]:
df.tail()

Name  Grade  Score
1  Sarang      3  23000
2  Jiemae      4  44000
3   Yeoin      2  52000
4   James      3  55000
5     Sen      4  60000

####  3) 형태(크기) 확인

In [73]:
df.shape

(6, 3)

####  4) 열확인

In [75]:
print(df.columns)
print(df.columns.values)
print(list(df))

Index(['Name', 'Grade', 'Score'], dtype='object')
['Name' 'Grade' 'Score']
['Name', 'Grade', 'Score']


####  5) 자료형 확인

In [76]:
df.dtypes  # 열 자료형 확인

Name     object
Grade     int64
Score     int64
dtype: object

In [77]:
df.info()   # 열 자료형, 값 개수 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Grade   6 non-null      int64 
 2   Score   6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes


#### 6) 기초통계정보

In [78]:
df.describe()  

Grade         Score
count  6.000000      6.000000
mean   2.833333  48333.333333
std    1.169045  13515.423288
min    1.000000  23000.000000
25%    2.250000  46000.000000
50%    3.000000  53500.000000
75%    3.750000  55750.000000
max    4.000000  60000.000000

In [80]:
df[['Score']].describe()

Score
count      6.000000
mean   48333.333333
std    13515.423288
min    23000.000000
25%    46000.000000
50%    53500.000000
75%    55750.000000
max    60000.000000

#### 7) 정렬해서 보기

In [87]:
df.sort_values(['Score', 'Grade'], ascending = [False,False]).head()

Name  Grade  Score
5      Sen      4  60000
0  Gildong      1  56000
4    James      3  52000
3    Yeoin      2  52000
2   Jiemae      4  44000

#### 8) 고유값 확인

In [90]:
df['Name'].unique()

array(['Gildong', 'Sarang', 'Jiemae', 'Yeoin', 'James', 'Sen'],
      dtype=object)

#### 9) 고유값과 개수 확인

In [91]:
df['Score'].value_counts()

52000    2
56000    1
23000    1
44000    1
60000    1
Name: Score, dtype: int64

#### 10) 기본 집계

In [7]:
print(df[['Score', 'Grade']].median())
print('-'*25)
print(df[['Score', 'Grade']].mean())
print('-'*25)
print(df[['Score', 'Grade']].min())
print('-'*25)
print(df[['Score', 'Grade']].max())
print('-'*25)
print(df[['Score', 'Grade']].sum())

Score    52000.0
Grade        3.0
dtype: float64
-------------------------
Score    47833.333333
Grade        2.833333
dtype: float64
-------------------------
Score    23000
Grade        1
dtype: int64
-------------------------
Score    60000
Grade        4
dtype: int64
-------------------------
Score    287000
Grade        17
dtype: int64


#### 11) 2차원으로 특정 열 호출

In [93]:
df[['Score', 'Grade']]

Score  Grade
0  56000      1
1  23000      3
2  44000      4
3  52000      2
4  52000      3
5  60000      4

#### 12) 조회하기

- 여러 조건 조회

In [97]:
df.loc[(df['Score']> 55000) & (df['Grade'] >2)]

Name  Grade  Score
5  Sen      4  60000

- isin([a,b]) : a값 또는 b값 데이터만 조회

In [100]:
df.loc[df['Grade'].isin([1,2])]

Name  Grade  Score
0  Gildong      1  56000
3    Yeoin      2  52000

- between(a,b) : a값부터 b값까지 범위 안의 데이터 조회

In [102]:
df.loc[df['Grade'].between(2,4)]

Name  Grade  Score
1  Sarang      3  23000
2  Jiemae      4  44000
3   Yeoin      2  52000
4   James      3  52000
5     Sen      4  60000

In [110]:
df.loc[df['Score']>52000,['Name', 'Score']]

Name  Score
0  Gildong  56000
5      Sen  60000

## 그 외 함수들
#### np.zero()
- 0으로 채워진 배열 생성

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### np.ones()
- 1로 채워진 배열

In [13]:
np.ones((1,2))

array([[1., 1.]])

#### np.full()
- 특정 값으로 채워진 배열

In [15]:
np.full((2,2), 7.)

array([[7., 7.],
       [7., 7.]])

#### np.eye()
- 정방향 행렬

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

#### np.random.random()
- 랜덤 값으로 채운 배열

In [17]:
np.random.random((2,2))

array([[0.53566952, 0.10234268],
       [0.81023832, 0.33796221]])