In [2]:
# 라이브러리 불러오기
import numpy as np

**배열 용어 정의**
- axis : 배열의 각 축
- rank : 축의 개수
- shape : 축의 길이, 배열의 크기

**배열 만들기**
- np.array() 함수를 사용해서 배열을 만듭니다

In [3]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]
b1 = np.array(a1)
print(b1)

[1 2 3 4 5]


In [4]:
# 2차원 리스트
a2 = [[1.5, 2.5, 3.2],[4.2, 5.7, 6.4]]
b2 = np.array(a2)
print(b2)

[[1.5 2.5 3.2]
 [4.2 5.7 6.4]]


In [5]:
# 3차원 리스트
a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
b3 = np.array(a3)
print(b3)

[[[1 3 1]
  [4 7 6]
  [8 3 4]]

 [[6 2 4]
  [8 1 5]
  [3 5 9]]]


**차원 확인**
- ndim 속성으로 배열 차원을 확인합니다

In [6]:
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

1
2
3


**형태크기확인**
- shape 속성으로 배열 형태를 확인합니다
    - 1차원 : (x,)
    - 2차원 : (x, y)
    - 3차원 : (x, y, z)

In [7]:
print(b1.shape)
print(b2.shape)
print(b3.shape)

(5,)
(2, 3)
(2, 3, 3)


**요소 자료형 확인**
- dtype 속성으로 배열에 포함된 요소들의 자료형을 확인합니다
- 배열은 한가지 자료형만 가질 수 있습니다

In [8]:
print(b1.dtype)
print(b2.dtype)
print(b3.dtype)

int32
float64
int32


**Reshape**
- 요소 개수만 변하지 않으면 다양한 형태로 변환 가능하다

In [9]:
# 2차원 배열만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
# 1차원 배열로 Reshape
c = a.reshape(6)
print(c)

[1 2 3 4 5 6]


**-1의 편리성**
- (n, -1) 또는 (-1, n) 으로 행 또는 열 크기 한 쪽만 지정할 수 있다

In [22]:
print(a.reshape(1, -1)) # 1행으로 나타내기
print(a.reshape(3, -1)) # 3행으로 나타내기
print(a.reshape(-1, 2)) # 2열로 나타내기
print(a.reshape(-1, 3)) # 3열로 나타내기

[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


**인덱싱**

In [34]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a)
print()

print(a[0, 1])
print()

print(a[[0, 1]])
print()

print(a[[0, 1, 2]])
print()

print(a[ : ,[0, 1]])
print()

print(a[[1], [1]])
print()

print(a[[2], [1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

2

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]
 [7 8]]

[5]

[8]


**슬라이싱**

In [39]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a)
print()

print(a[0:2])
print()

print(a[0, 0:2])
print()

print(a[ : , 1:3])
print()

print(a[1:, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]

[1 2]

[[2 3]
 [5 6]
 [8 9]]

[[5 6]
 [8 9]]


**조건 조회**
- 불리안 방식이라고 부르며, 조회 결과는 1차원 배열입니다

In [42]:
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 90이상인 것만 조회
print(score[score >= 90])
print()

condition = score >= 90
print(score[condition])
print()

# 90이상 95미만인 것만 조회
print(score[(score >= 90) & (score < 95)])

[91 93 96 91]

[91 93 96 91]

[91 93 91]


**배열 연산**

In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x)
print(y)
print()

# 배열 더하기
print(x + y)
print(np.add(x, y))
print()

# 배열 빼기
print(x - y)
print(np.subtract(x, y))
print()

# 배열 곱하기
print(x * y)
print(np.multiply(x, y))
print()

# 배열 나누기
print(x / y)
print(np.divide(x, y))
print()

# 배열 제곱
print(x ** y)
print(np.power(x, y))
print()

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]



**배열 집계**
- np.sum() 또는 array.sum()
    - axis = 0 : 열 기준 집계
    - axis = 1 : 행 기준 집계
    - 생략하면 전체 집계
- np.max(), np.min(), np.mean(), np.std(), np.argmax(), np.ardmin()

In [49]:
a = np.array([[1,5,7],
              [2,3,8]])

# 전체 집계
print(np.sum(a))

# 열 기준 집계
print(np.sum(a, axis = 0))

# 행 기준 집계
print(np.sum(a, axis = 1))

26
[ 3  8 15]
[13 13]


In [52]:
# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(a))

# 행 방향 최댓값의 인덱스
print(np.argmax(a, axis = 1))

# 열 방향 최댓값의 인덱스
print(np.argmax(a, axis = 0))

5
[2 2]
[1 0 1]
