# 선형 회귀

In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
boston = fetch_california_housing()

In [3]:
x = boston.data
y = boston.target

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [5]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

In [6]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((14448, 8), (6192, 8), (14448,), (6192,))

In [7]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(shape=(x_train.shape[1],)))
model.add(keras.layers.Dense(1, activation='linear'))

# 4. model complie
model.compile(loss = 'mse', optimizer='adam')

In [8]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_loss',
                  patience=5,
                  min_delta=0,
                  verbose = 1,
                  restore_best_weights=True)

In [9]:
model.fit(x_train, y_train, epochs=50, verbose=1,
         callbacks=[es], validation_split=0.2)

Epoch 1/50
362/362 [==============================] - 2s 3ms/step - loss: 1199797.3750 - val_loss: 670376.1875
Epoch 2/50
362/362 [==============================] - 1s 2ms/step - loss: 419899.9375 - val_loss: 208239.7500
Epoch 3/50
362/362 [==============================] - 1s 2ms/step - loss: 115770.0938 - val_loss: 46472.7539
Epoch 4/50
362/362 [==============================] - 1s 2ms/step - loss: 23704.8203 - val_loss: 8530.6924
Epoch 5/50
362/362 [==============================] - 1s 2ms/step - loss: 5241.5146 - val_loss: 2853.7427
Epoch 6/50
362/362 [==============================] - 1s 2ms/step - loss: 2537.3315 - val_loss: 2002.6222
Epoch 7/50
362/362 [==============================] - 1s 2ms/step - loss: 1939.3683 - val_loss: 1590.1091
Epoch 8/50
362/362 [==============================] - 1s 2ms/step - loss: 1503.8524 - val_loss: 1202.0979
Epoch 9/50
362/362 [==============================] - 1s 2ms/step - loss: 1112.7146 - val_loss: 857.2009
Epoch 10/50
362/362 [=============

In [10]:
model.evaluate(x_test, y_test)

194/194 [==============================] - 0s 2ms/step - loss: 1.5150


1.5149853229522705

In [11]:
print('정답 : ', y_test[:5])
print('예측 값 : ', model.predict(x_test).reshape(-1)[:5])

정답 :  [2.234 1.446 2.821 2.44  1.512]
194/194 [==============================] - 0s 1ms/step
예측 값 :  [1.8287454 3.056828  2.766028  2.7012477 3.191504 ]


# 이진분류(로지스틱)

In [37]:
from sklearn.datasets import load_breast_cancer

In [38]:
cancer = load_breast_cancer()

In [39]:
x = cancer.data
y = cancer.target

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [41]:
import tensorflow as tf
from tensorflow import keras

In [42]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((398, 30), (398,), (171, 30), (171,))

In [43]:
# 세션 클리어
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 블록 조립
model.add(keras.layers.Input(shape=(x_train.shape[1])))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# compile
model.compile(loss = 'binary_crossentropy', metrics=['accuracy'], optimizer='adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [44]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_loss',
                  patience=5,
                  min_delta=0,
                  verbose = 1,
                  restore_best_weights=True)

In [45]:
model.fit(x_train, y_train, verbose=1, epochs=50,
         callbacks=[es], validation_split=0.2)

Epoch 1/50
10/10 [==============================] - 1s 28ms/step - loss: 169.5105 - accuracy: 0.6289 - val_loss: 173.4468 - val_accuracy: 0.6000
Epoch 2/50
10/10 [==============================] - 0s 7ms/step - loss: 159.0126 - accuracy: 0.6289 - val_loss: 162.4577 - val_accuracy: 0.6000
Epoch 3/50
10/10 [==============================] - 0s 7ms/step - loss: 148.4431 - accuracy: 0.6289 - val_loss: 151.5484 - val_accuracy: 0.6000
Epoch 4/50
10/10 [==============================] - 0s 7ms/step - loss: 138.3109 - accuracy: 0.6289 - val_loss: 140.4465 - val_accuracy: 0.6000
Epoch 5/50
10/10 [==============================] - 0s 7ms/step - loss: 127.6514 - accuracy: 0.6289 - val_loss: 129.5953 - val_accuracy: 0.6000
Epoch 6/50
10/10 [==============================] - 0s 7ms/step - loss: 117.5310 - accuracy: 0.6289 - val_loss: 118.5698 - val_accuracy: 0.6000
Epoch 7/50
10/10 [==============================] - 0s 7ms/step - loss: 107.4591 - accuracy: 0.6289 - val_loss: 107.3888 - val_accuracy

In [46]:
model.evaluate(x_test, y_test)

6/6 [==============================] - 0s 2ms/step - loss: 1.4045 - accuracy: 0.8596


[1.4044506549835205, 0.859649121761322]

In [47]:
print('정답 : ', y_test[:5])
print('예측 값 : ', model.predict(x_test).reshape(-1)[:5])

정답 :  [1 1 1 1 1]
6/6 [==============================] - 0s 2ms/step
예측 값 :  [9.6178120e-01 9.7514051e-01 9.9999988e-01 9.9992663e-01 1.9067709e-10]


# 다중분류

In [48]:
from sklearn.datasets import load_iris

In [49]:
iris = load_iris()

In [50]:
x = iris.data
y = iris.target

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [52]:
import tensorflow as tf
from tensorflow import keras

In [53]:
from tensorflow.keras.utils import to_categorical

len_y= len(set(y_test))
y_train = to_categorical(y_train, len_y)
y_test = to_categorical(y_test,len_y)

In [71]:
x_train.shape, y_train.shape, y_test.shape
# x_train.shape[1]

((105, 4), (105, 3), (45, 3))

In [77]:
# 세션 클리어
keras.backend.clear_session()

# 모델 발판 만들기
model = keras.models.Sequential()

# 모델 블록 조립
model.add(keras.layers.Input(shape = (x_train.shape[1],)))
model.add(keras.layers.Dense(3, activation = 'softmax'))

# 모델 컴파일
model.compile(loss = 'categorical_crossentropy', metrics=['accuracy'],
              optimizer = 'adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [78]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_loss',
                  patience=5,
                  min_delta=0,
                  verbose = 1,
                  restore_best_weights=True)

In [79]:
model.fit(x_train, y_train, epochs=50, verbose=1,
         callbacks=[es], validation_split=0.2)

Epoch 1/50
3/3 [==============================] - 1s 228ms/step - loss: 7.0586 - accuracy: 0.3095 - val_loss: 6.2212 - val_accuracy: 0.3810
Epoch 2/50
3/3 [==============================] - 0s 22ms/step - loss: 6.9888 - accuracy: 0.3095 - val_loss: 6.1598 - val_accuracy: 0.3810
Epoch 3/50
3/3 [==============================] - 0s 21ms/step - loss: 6.9228 - accuracy: 0.3095 - val_loss: 6.0984 - val_accuracy: 0.3810
Epoch 4/50
3/3 [==============================] - 0s 21ms/step - loss: 6.8536 - accuracy: 0.3095 - val_loss: 6.0373 - val_accuracy: 0.3810
Epoch 5/50
3/3 [==============================] - 0s 22ms/step - loss: 6.7843 - accuracy: 0.3095 - val_loss: 5.9763 - val_accuracy: 0.3810
Epoch 6/50
3/3 [==============================] - 0s 22ms/step - loss: 6.7161 - accuracy: 0.3095 - val_loss: 5.9151 - val_accuracy: 0.3810
Epoch 7/50
3/3 [==============================] - 0s 22ms/step - loss: 6.6486 - accuracy: 0.3095 - val_loss: 5.8537 - val_accuracy: 0.3810
Epoch 8/50
3/3 [==========

In [80]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 5ms/step - loss: 3.5714 - accuracy: 0.3556


[3.5713961124420166, 0.35555556416511536]

In [83]:
print('정답 : ', y_test[:5])
print('예측 값 : ', model.predict(x_test)[:5])

정답 :  [[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2/2 [==============================] - 0s 3ms/step
예측 값 :  [[9.6633428e-01 3.6144638e-04 3.3304259e-02]
 [9.7978473e-01 1.7520797e-02 2.6943912e-03]
 [9.6743351e-01 1.0205171e-03 3.1546030e-02]
 [9.8214573e-01 1.1888525e-02 5.9656845e-03]
 [9.7032398e-01 2.6496714e-02 3.1793963e-03]]
