##Linear Regression##

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = np.array(range(20))
y = x * 2 - 1 
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
keras.backend.clear_session()

model = keras.models.Sequential()


model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

model.compile(loss='mse', optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 740ms/step - loss: 51.9827
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 51.8113
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 51.6401
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 51.4693
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 51.2987
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 51.1285
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 50.9586
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 50.7889
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 50.6197
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 50.4507


In [ ]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 102ms/step


array([9.9940868e-03, 1.2959701e+00, 2.5819461e+00, 3.8679223e+00,
       5.1538982e+00, 6.4398742e+00, 7.7258506e+00, 9.0118265e+00,
       1.0297803e+01, 1.1583779e+01, 1.2869755e+01, 1.4155731e+01,
       1.5441708e+01, 1.6727684e+01, 1.8013659e+01, 1.9299635e+01,
       2.0585611e+01, 2.1871588e+01, 2.3157564e+01, 2.4443539e+01],
      dtype=float32)

##Logistic Regression##

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [ ]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

print(y)
print(model.predict(x))

Epoch 1/10
1/1 [==============================] - 1s 681ms/step - loss: 6.4737 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 18ms/step - loss: 6.4661 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 18ms/step - loss: 6.4584 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 6.4508 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 15ms/step - loss: 6.4431 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 6.4355 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 6.4278 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 6.4202 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 6.4125 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 6.4049 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1

##Multi calss##

In [17]:
from sklearn.datasets import load_iris
from tensorflow.keras.utils import to_categorical

In [18]:
iris = load_iris()
x = iris.data
y = iris.target

In [19]:
x.shape, y.shape

((150, 4), (150,))

In [22]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
y = to_categorical(y, 3)

In [24]:
x.shape, y.shape

((150, 4), (150, 3))

In [25]:
keras.backend.clear_session()
model = keras.models.Sequential()
model.add(keras.layers.Input(shape=(4,)))
model.add(keras.layers.Dense(3, activation ='softmax'))
model.compile(loss = 'categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(x, y, epochs = 10, verbose = 1)

Epoch 1/10
5/5 [==============================] - 1s 8ms/step - loss: 5.6466 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 5.5592 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 5.4742 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 5.3854 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 5.3024 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 5.2143 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 5.1332 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 5.0500 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 4.9675 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 4.8871 - accuracy: 0.3333


In [27]:
y_pred = model.predict(x)

5/5 [==============================] - 0s 3ms/step


In [28]:
y_pred[:5]

array([[3.7138849e-01, 6.2856919e-01, 4.2277719e-05],
       [3.4743413e-01, 6.5246868e-01, 9.7142656e-05],
       [3.8058066e-01, 6.1932844e-01, 9.0869529e-05],
       [3.1527537e-01, 6.8461370e-01, 1.1091254e-04],
       [3.7285256e-01, 6.2710673e-01, 4.0708426e-05]], dtype=float32)

In [29]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)