<a href="https://colab.research.google.com/github/Run-aivle/study/blob/main/study/Feb/02.28/DL(HiddenLayer).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 회귀

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
house = fetch_california_housing()

In [ ]:
x = house.data
y = house.target

In [ ]:
x.shape, y.shape

((20640, 8), (20640,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [ ]:
x_train.shape, x_test.shape, y_train.shape

((14448, 8), (6192, 8), (14448,))

### 모델링

* Sequential 모델
* 회귀
* 히든 레이어 2개 이상 생성('relu', 'swift')

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(shape=(x_train.shape[1],)))
model.add(keras.layers.Dense(256, activation = 'relu'))
model.add(keras.layers.Dense(128, activation = 'swish'))
model.add(keras.layers.Dense(32, activation = 'relu'))
model.add(keras.layers.Dense(1, activation = 'linear'))

# 4. 모델 컴파일 
model.compile(loss = 'mse', optimizer = 'adam')

# 5. 모델 요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               2304      
                                                                 
 dense_1 (Dense)             (None, 128)               32896     
                                                                 
 dense_2 (Dense)             (None, 32)                4128      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 39,361
Trainable params: 39,361
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor ='vasl_loss',
                   patience = 5,
                   min_delta = 0,
                   verbose = 1,
                   restore_best_weights = True)

In [ ]:
model.fit(x_train, y_train, epochs= 100, verbose = 1,
          validation_split = 0.2, callbacks = [es])

Epoch 1/100
354/362 [============================>.] - ETA: 0s - loss: 67.2582

362/362 [==============================] - 9s 7ms/step - loss: 66.2513 - val_loss: 35.8741
Epoch 2/100
361/362 [============================>.] - ETA: 0s - loss: 2.8782

362/362 [==============================] - 1s 4ms/step - loss: 2.8773 - val_loss: 1.8184
Epoch 3/100
355/362 [============================>.] - ETA: 0s - loss: 1.1966

362/362 [==============================] - 1s 4ms/step - loss: 1.2170 - val_loss: 4.8850
Epoch 4/100
353/362 [============================>.] - ETA: 0s - loss: 16.5629

362/362 [==============================] - 1s 4ms/step - loss: 16.2087 - val_loss: 1.1616
Epoch 5/100
348/362 [===========================>..] - ETA: 0s - loss: 1.0679

362/362 [==============================] - 1s 4ms/step - loss: 1.0606 - val_loss: 1.7060
Epoch 6/100
361/362 [============================>.] - ETA: 0s - loss: 1.3272

362/362 [==============================] - 1s 4ms/step - loss: 1.3306 - val_loss: 1.7304
Epoch 7/100
362/362 [==============================] - ETA: 0s - loss: 4.1093

362/362 [==============================] - 1s 4ms/step - loss: 4.1093 - val_loss: 0.7260
Epoch 8/100
351/362 [============================>.] - ETA: 0s - loss: 0.8640

362/362 [==============================] - 2s 4ms/step - loss: 0.8742 - val_loss: 1.4842
Epoch 9/100
362/362 [==============================] - ETA: 0s - loss: 4.4562

362/362 [==============================] - 2s 5ms/step - loss: 4.4562 - val_loss: 0.7158
Epoch 10/100
353/362 [============================>.] - ETA: 0s - loss: 1.4859

362/362 [==============================] - 1s 4ms/step - loss: 1.4706 - val_loss: 0.7866
Epoch 11/100
360/362 [============================>.] - ETA: 0s - loss: 3.0162

362/362 [==============================] - 1s 4ms/step - loss: 3.0119 - val_loss: 1.8201
Epoch 12/100
355/362 [============================>.] - ETA: 0s - loss: 1.1363

362/362 [==============================] - 1s 4ms/step - loss: 1.1339 - val_loss: 1.9362
Epoch 13/100
350/362 [============================>.] - ETA: 0s - loss: 0.9499

362/362 [==============================] - 1s 4ms/step - loss: 0.9378 - val_loss: 0.6357
Epoch 14/100
360/362 [============================>.] - ETA: 0s - loss: 0.8957

362/362 [==============================] - 1s 4ms/step - loss: 0.8946 - val_loss: 1.2982
Epoch 15/100
360/362 [============================>.] - ETA: 0s - loss: 1.3567

362/362 [==============================] - 1s 4ms/step - loss: 1.3552 - val_loss: 3.7237
Epoch 16/100
351/362 [============================>.] - ETA: 0s - loss: 1.0468

362/362 [==============================] - 1s 4ms/step - loss: 1.0366 - val_loss: 0.6683
Epoch 17/100
353/362 [============================>.] - ETA: 0s - loss: 1.0098

362/362 [==============================] - 2s 5ms/step - loss: 1.0031 - val_loss: 0.8135
Epoch 18/100
355/362 [============================>.] - ETA: 0s - loss: 0.9797

362/362 [==============================] - 1s 4ms/step - loss: 0.9761 - val_loss: 0.6744
Epoch 19/100
362/362 [==============================] - ETA: 0s - loss: 1.0159

362/362 [==============================] - 1s 4ms/step - loss: 1.0159 - val_loss: 0.6482
Epoch 20/100
350/362 [============================>.] - ETA: 0s - loss: 0.6530

362/362 [==============================] - 1s 4ms/step - loss: 0.6549 - val_loss: 0.8336
Epoch 21/100
346/362 [===========================>..] - ETA: 0s - loss: 0.6929

362/362 [==============================] - 1s 4ms/step - loss: 0.6941 - val_loss: 0.7568
Epoch 22/100
361/362 [============================>.] - ETA: 0s - loss: 0.7929

362/362 [==============================] - 1s 4ms/step - loss: 0.7926 - val_loss: 0.9030
Epoch 23/100
346/362 [===========================>..] - ETA: 0s - loss: 0.7330

362/362 [==============================] - 1s 4ms/step - loss: 0.7388 - val_loss: 0.6148
Epoch 24/100
346/362 [===========================>..] - ETA: 0s - loss: 0.8739

362/362 [==============================] - 1s 4ms/step - loss: 0.8661 - val_loss: 0.6138
Epoch 25/100
360/362 [============================>.] - ETA: 0s - loss: 0.6431

362/362 [==============================] - 2s 5ms/step - loss: 0.6427 - val_loss: 0.6003
Epoch 26/100
354/362 [============================>.] - ETA: 0s - loss: 0.6428

362/362 [==============================] - 1s 4ms/step - loss: 0.6414 - val_loss: 0.6920
Epoch 27/100
350/362 [============================>.] - ETA: 0s - loss: 1.2056

362/362 [==============================] - 1s 4ms/step - loss: 1.1939 - val_loss: 0.7104
Epoch 28/100
355/362 [============================>.] - ETA: 0s - loss: 0.7694

362/362 [==============================] - 1s 4ms/step - loss: 0.7669 - val_loss: 0.6391
Epoch 29/100
362/362 [==============================] - ETA: 0s - loss: 0.6292

362/362 [==============================] - 1s 4ms/step - loss: 0.6292 - val_loss: 0.5733
Epoch 30/100
356/362 [============================>.] - ETA: 0s - loss: 0.6300

362/362 [==============================] - 1s 4ms/step - loss: 0.6330 - val_loss: 0.7203
Epoch 31/100
348/362 [===========================>..] - ETA: 0s - loss: 0.6581

362/362 [==============================] - 1s 4ms/step - loss: 0.6493 - val_loss: 0.5732
Epoch 32/100
358/362 [============================>.] - ETA: 0s - loss: 0.6217

362/362 [==============================] - 1s 4ms/step - loss: 0.6217 - val_loss: 0.5462
Epoch 33/100
356/362 [============================>.] - ETA: 0s - loss: 0.6277

362/362 [==============================] - 2s 5ms/step - loss: 0.6263 - val_loss: 0.5569
Epoch 34/100
351/362 [============================>.] - ETA: 0s - loss: 0.6169

362/362 [==============================] - 1s 4ms/step - loss: 0.6141 - val_loss: 0.8673
Epoch 35/100
351/362 [============================>.] - ETA: 0s - loss: 0.5906

362/362 [==============================] - 1s 4ms/step - loss: 0.5926 - val_loss: 0.6723
Epoch 36/100
360/362 [============================>.] - ETA: 0s - loss: 0.6665

362/362 [==============================] - 1s 4ms/step - loss: 0.6663 - val_loss: 0.7030
Epoch 37/100
352/362 [============================>.] - ETA: 0s - loss: 0.6020

362/362 [==============================] - 1s 4ms/step - loss: 0.6010 - val_loss: 0.9650
Epoch 38/100
349/362 [===========================>..] - ETA: 0s - loss: 0.6116

362/362 [==============================] - 1s 4ms/step - loss: 0.6093 - val_loss: 0.5792
Epoch 39/100
354/362 [============================>.] - ETA: 0s - loss: 0.5593

362/362 [==============================] - 1s 4ms/step - loss: 0.5623 - val_loss: 0.7930
Epoch 40/100
351/362 [============================>.] - ETA: 0s - loss: 0.5358

362/362 [==============================] - 1s 4ms/step - loss: 0.5417 - val_loss: 0.5295
Epoch 41/100
360/362 [============================>.] - ETA: 0s - loss: 0.5387

362/362 [==============================] - 2s 5ms/step - loss: 0.5401 - val_loss: 0.7710
Epoch 42/100
360/362 [============================>.] - ETA: 0s - loss: 0.5583

362/362 [==============================] - 2s 4ms/step - loss: 0.5581 - val_loss: 0.5362
Epoch 43/100
360/362 [============================>.] - ETA: 0s - loss: 0.5307

362/362 [==============================] - 1s 4ms/step - loss: 0.5317 - val_loss: 0.5542
Epoch 44/100
356/362 [============================>.] - ETA: 0s - loss: 0.8954

362/362 [==============================] - 1s 4ms/step - loss: 0.8898 - val_loss: 0.5362
Epoch 45/100
350/362 [============================>.] - ETA: 0s - loss: 0.5360

362/362 [==============================] - 1s 4ms/step - loss: 0.5387 - val_loss: 0.5192
Epoch 46/100
354/362 [============================>.] - ETA: 0s - loss: 0.5582

362/362 [==============================] - 1s 4ms/step - loss: 0.5554 - val_loss: 0.7831
Epoch 47/100
362/362 [==============================] - ETA: 0s - loss: 0.5215

362/362 [==============================] - 1s 4ms/step - loss: 0.5215 - val_loss: 0.5410
Epoch 48/100
349/362 [===========================>..] - ETA: 0s - loss: 0.5187

362/362 [==============================] - 1s 4ms/step - loss: 0.5195 - val_loss: 0.5822
Epoch 49/100
362/362 [==============================] - ETA: 0s - loss: 0.5392

362/362 [==============================] - 1s 4ms/step - loss: 0.5392 - val_loss: 0.5868
Epoch 50/100
345/362 [===========================>..] - ETA: 0s - loss: 0.5248

362/362 [==============================] - 2s 4ms/step - loss: 0.5231 - val_loss: 0.4975
Epoch 51/100
354/362 [============================>.] - ETA: 0s - loss: 0.5239

362/362 [==============================] - 1s 4ms/step - loss: 0.5253 - val_loss: 0.5130
Epoch 52/100
348/362 [===========================>..] - ETA: 0s - loss: 0.5396

362/362 [==============================] - 1s 4ms/step - loss: 0.5408 - val_loss: 0.5830
Epoch 53/100
361/362 [============================>.] - ETA: 0s - loss: 0.5131

362/362 [==============================] - 1s 4ms/step - loss: 0.5129 - val_loss: 0.5886
Epoch 54/100
353/362 [============================>.] - ETA: 0s - loss: 0.5071

362/362 [==============================] - 1s 4ms/step - loss: 0.5045 - val_loss: 0.5363
Epoch 55/100
362/362 [==============================] - ETA: 0s - loss: 0.5419

362/362 [==============================] - 1s 4ms/step - loss: 0.5419 - val_loss: 0.5006
Epoch 56/100
361/362 [============================>.] - ETA: 0s - loss: 0.5026

362/362 [==============================] - 1s 4ms/step - loss: 0.5025 - val_loss: 0.5437
Epoch 57/100
356/362 [============================>.] - ETA: 0s - loss: 0.5162

362/362 [==============================] - 1s 4ms/step - loss: 0.5157 - val_loss: 0.5379
Epoch 58/100
353/362 [============================>.] - ETA: 0s - loss: 0.4964

362/362 [==============================] - 2s 5ms/step - loss: 0.4977 - val_loss: 0.8124
Epoch 59/100
355/362 [============================>.] - ETA: 0s - loss: 0.5228

362/362 [==============================] - 2s 5ms/step - loss: 0.5211 - val_loss: 0.5046
Epoch 60/100
354/362 [============================>.] - ETA: 0s - loss: 0.4831

362/362 [==============================] - 1s 4ms/step - loss: 0.4814 - val_loss: 0.5013
Epoch 61/100
360/362 [============================>.] - ETA: 0s - loss: 0.5052

362/362 [==============================] - 1s 4ms/step - loss: 0.5056 - val_loss: 0.4965
Epoch 62/100
349/362 [===========================>..] - ETA: 0s - loss: 0.4918

362/362 [==============================] - 1s 4ms/step - loss: 0.4882 - val_loss: 0.5014
Epoch 63/100
360/362 [============================>.] - ETA: 0s - loss: 0.4927

362/362 [==============================] - 1s 4ms/step - loss: 0.4922 - val_loss: 0.5303
Epoch 64/100
356/362 [============================>.] - ETA: 0s - loss: 0.4766

362/362 [==============================] - 1s 4ms/step - loss: 0.4759 - val_loss: 0.4843
Epoch 65/100
358/362 [============================>.] - ETA: 0s - loss: 0.4972

362/362 [==============================] - 2s 5ms/step - loss: 0.4949 - val_loss: 0.4799
Epoch 66/100
362/362 [==============================] - ETA: 0s - loss: 0.4864

362/362 [==============================] - 2s 4ms/step - loss: 0.4864 - val_loss: 0.4753
Epoch 67/100
358/362 [============================>.] - ETA: 0s - loss: 0.4850

362/362 [==============================] - 1s 4ms/step - loss: 0.4864 - val_loss: 0.4849
Epoch 68/100
346/362 [===========================>..] - ETA: 0s - loss: 0.4982

362/362 [==============================] - 1s 4ms/step - loss: 0.4967 - val_loss: 0.4783
Epoch 69/100
355/362 [============================>.] - ETA: 0s - loss: 0.4714

362/362 [==============================] - 1s 4ms/step - loss: 0.4727 - val_loss: 0.4949
Epoch 70/100
358/362 [============================>.] - ETA: 0s - loss: 0.4787

362/362 [==============================] - 1s 4ms/step - loss: 0.4797 - val_loss: 0.4918
Epoch 71/100
357/362 [============================>.] - ETA: 0s - loss: 0.4867

362/362 [==============================] - 1s 4ms/step - loss: 0.4870 - val_loss: 0.5158
Epoch 72/100
360/362 [============================>.] - ETA: 0s - loss: 0.4752

362/362 [==============================] - 1s 4ms/step - loss: 0.4751 - val_loss: 0.4866
Epoch 73/100
352/362 [============================>.] - ETA: 0s - loss: 0.4856

362/362 [==============================] - 2s 4ms/step - loss: 0.4883 - val_loss: 0.5568
Epoch 74/100
351/362 [============================>.] - ETA: 0s - loss: 0.4812

362/362 [==============================] - 2s 4ms/step - loss: 0.4845 - val_loss: 0.5899
Epoch 75/100
358/362 [============================>.] - ETA: 0s - loss: 0.4873

362/362 [==============================] - 1s 4ms/step - loss: 0.4874 - val_loss: 0.5181
Epoch 76/100
353/362 [============================>.] - ETA: 0s - loss: 0.4855

362/362 [==============================] - 1s 4ms/step - loss: 0.4855 - val_loss: 0.4828
Epoch 77/100
356/362 [============================>.] - ETA: 0s - loss: 0.4653

362/362 [==============================] - 1s 4ms/step - loss: 0.4645 - val_loss: 0.6530
Epoch 78/100
345/362 [===========================>..] - ETA: 0s - loss: 0.4848

362/362 [==============================] - 1s 4ms/step - loss: 0.4830 - val_loss: 0.4778
Epoch 79/100
355/362 [============================>.] - ETA: 0s - loss: 0.4713

362/362 [==============================] - 1s 4ms/step - loss: 0.4688 - val_loss: 0.5142
Epoch 80/100
356/362 [============================>.] - ETA: 0s - loss: 0.4808

362/362 [==============================] - 1s 4ms/step - loss: 0.4796 - val_loss: 0.5525
Epoch 81/100
359/362 [============================>.] - ETA: 0s - loss: 0.4610

362/362 [==============================] - 2s 4ms/step - loss: 0.4605 - val_loss: 0.4988
Epoch 82/100
360/362 [============================>.] - ETA: 0s - loss: 0.4738

362/362 [==============================] - 2s 5ms/step - loss: 0.4733 - val_loss: 1.3512
Epoch 83/100
360/362 [============================>.] - ETA: 0s - loss: 0.4736

362/362 [==============================] - 1s 4ms/step - loss: 0.4743 - val_loss: 0.5145
Epoch 84/100
352/362 [============================>.] - ETA: 0s - loss: 0.4680

362/362 [==============================] - 1s 4ms/step - loss: 0.4664 - val_loss: 0.6225
Epoch 85/100
359/362 [============================>.] - ETA: 0s - loss: 0.4658

362/362 [==============================] - 1s 4ms/step - loss: 0.4666 - val_loss: 1.2669
Epoch 86/100
351/362 [============================>.] - ETA: 0s - loss: 0.5141

362/362 [==============================] - 1s 4ms/step - loss: 0.5143 - val_loss: 0.6569
Epoch 87/100
357/362 [============================>.] - ETA: 0s - loss: 0.4639

362/362 [==============================] - 1s 4ms/step - loss: 0.4654 - val_loss: 0.6039
Epoch 88/100
350/362 [============================>.] - ETA: 0s - loss: 0.4652

362/362 [==============================] - 1s 4ms/step - loss: 0.4647 - val_loss: 0.5006
Epoch 89/100
360/362 [============================>.] - ETA: 0s - loss: 0.4586

362/362 [==============================] - 1s 4ms/step - loss: 0.4583 - val_loss: 0.4733
Epoch 90/100
352/362 [============================>.] - ETA: 0s - loss: 0.4607

362/362 [==============================] - 2s 5ms/step - loss: 0.4615 - val_loss: 0.5244
Epoch 91/100
346/362 [===========================>..] - ETA: 0s - loss: 0.4598

362/362 [==============================] - 1s 4ms/step - loss: 0.4608 - val_loss: 0.5296
Epoch 92/100
354/362 [============================>.] - ETA: 0s - loss: 0.4679

362/362 [==============================] - 1s 4ms/step - loss: 0.4675 - val_loss: 0.5090
Epoch 93/100
353/362 [============================>.] - ETA: 0s - loss: 0.4606

362/362 [==============================] - 1s 4ms/step - loss: 0.4609 - val_loss: 0.4946
Epoch 94/100
349/362 [===========================>..] - ETA: 0s - loss: 0.4724

362/362 [==============================] - 1s 4ms/step - loss: 0.4736 - val_loss: 0.5053
Epoch 95/100
346/362 [===========================>..] - ETA: 0s - loss: 0.4657

362/362 [==============================] - 1s 4ms/step - loss: 0.4639 - val_loss: 0.4797
Epoch 96/100
353/362 [============================>.] - ETA: 0s - loss: 0.4584

362/362 [==============================] - 1s 4ms/step - loss: 0.4563 - val_loss: 0.4926
Epoch 97/100
353/362 [============================>.] - ETA: 0s - loss: 0.4560

362/362 [==============================] - 1s 4ms/step - loss: 0.4568 - val_loss: 0.5053
Epoch 98/100
347/362 [===========================>..] - ETA: 0s - loss: 0.4524

362/362 [==============================] - 2s 5ms/step - loss: 0.4537 - val_loss: 0.5031
Epoch 99/100
355/362 [============================>.] - ETA: 0s - loss: 0.4632

362/362 [==============================] - 1s 4ms/step - loss: 0.4635 - val_loss: 0.5012
Epoch 100/100
353/362 [============================>.] - ETA: 0s - loss: 0.4612

362/362 [==============================] - 1s 4ms/step - loss: 0.4597 - val_loss: 0.6251


In [ ]:
model.evaluate(x_train, y_train)

452/452 [==============================] - 1s 2ms/step - loss: 0.4777


0.47766223549842834

In [ ]:
y_pred = model.predict(x_test)

194/194 [==============================] - 0s 2ms/step


In [ ]:
y_test[:5]

array([5.00001, 4.048  , 1.414  , 2.75   , 2.575  ])

In [ ]:
y_pred.reshape(-1)[:5]

array([1.7699146, 3.1049893, 2.1522071, 2.082272 , 2.2617755],
      dtype=float32)

## 이진 분류(sigmoid)

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
cancer = load_breast_cancer()

In [ ]:
x = pd.DataFrame(cancer.data, columns = cancer.feature_names)
y = cancer.target

In [ ]:
x.shape, y.shape

((569, 30), (569,))

In [ ]:
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.15)

In [ ]:
x_train.shape, x_test.shape, y_train.shape

((483, 30), (86, 30), (483,))

* min-max scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train.min(), x_test.min() , x_train.max(), x_test.max()

(0.0, 0.0, 1.0, 1.2531723543180977)

### 모델링
* Sequential()
* hiddenlayer 2개 이상
* 이진 분류

In [ ]:
# 세션 클리어
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 블록 조립
model.add(keras.layers.Input(shape=(x_train.shape[1],)))
model.add(keras.layers.Dense(128, 'relu'))
model.add(keras.layers.Dense(64, 'swish'))
model.add(keras.layers.Dense(32, 'swish'))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

# 모델 컴파일
model.compile(loss = keras.losses.binary_crossentropy, metrics=['accuracy'],
              optimizer='adam')

# 모델 요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               3968      
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 14,337
Trainable params: 14,337
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

es = EarlyStopping(monitor = 'val_loss',
                   patience = 5, 
                   min_delta = 0,
                   verbose = 1,
                   restore_best_weights = True)

In [ ]:
model.fit(x_train, y_train, epochs=100, verbose = 1,
          callbacks = [es], validation_split = 0.1)

Epoch 1/100
14/14 [==============================] - 2s 23ms/step - loss: 0.6716 - accuracy: 0.7558 - val_loss: 0.6293 - val_accuracy: 0.9184
Epoch 2/100
14/14 [==============================] - 0s 7ms/step - loss: 0.5930 - accuracy: 0.8986 - val_loss: 0.5025 - val_accuracy: 0.9184
Epoch 3/100
14/14 [==============================] - 0s 8ms/step - loss: 0.4434 - accuracy: 0.9009 - val_loss: 0.3032 - val_accuracy: 0.9184
Epoch 4/100
14/14 [==============================] - 0s 6ms/step - loss: 0.2883 - accuracy: 0.9124 - val_loss: 0.1782 - val_accuracy: 0.8980
Epoch 5/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2152 - accuracy: 0.9078 - val_loss: 0.1321 - val_accuracy: 0.9388
Epoch 6/100
14/14 [==============================] - 0s 6ms/step - loss: 0.1807 - accuracy: 0.9217 - val_loss: 0.1328 - val_accuracy: 0.9184
Epoch 7/100
14/14 [==============================] - 0s 7ms/step - loss: 0.1578 - accuracy: 0.9309 - val_loss: 0.1140 - val_accuracy: 0.9184
Epoch 8/100


In [ ]:
print(model.evaluate(x_train, y_train))
print(model.evaluate(x_test, y_test))

16/16 [==============================] - 0s 3ms/step - loss: 0.0603 - accuracy: 0.9834
[0.06030303239822388, 0.9834368824958801]
3/3 [==============================] - 0s 5ms/step - loss: 0.0419 - accuracy: 0.9884
[0.04193754121661186, 0.9883720874786377]


In [ ]:
print(y_test[:5])
print(model.predict(x_test).reshape(-1)[:5])

[1 0 1 1 1]
3/3 [==============================] - 0s 3ms/step
[9.8001385e-01 1.8175637e-06 9.9615782e-01 9.9999917e-01 9.9902332e-01]


## 다중분류(softmax)

In [ ]:
from sklearn.datasets import load_wine

In [ ]:
wine = load_wine()

In [ ]:
x = pd.DataFrame(wine.data, columns = wine.feature_names)
y = wine.target

In [ ]:
x.head(2)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0

In [ ]:
x.shape, y.shape

((178, 13), (178,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [ ]:
x_train.shape, x_test.shape, y_train.shape

((151, 13), (27, 13), (151,))

* min-max scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train.min(), x_test.min(), x_train.max(), x_test.max()

(0.0, -0.2222222222222222, 1.0, 1.1193887297039158)

* One_hot_encoding


In [ ]:
class_n = len(set(y_train))

In [ ]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train,class_n)
y_test = to_categorical(y_test, class_n)

In [ ]:
x_train.shape, y_train.shape

((151, 13), (151, 3))

### 모델링
* hidden layer 수는 2개 이상
* Sequential()
* 다중분류

In [ ]:
# 세션 클리어
keras.backend.clear_session()

# 모델 선언
model = keras.models.Sequential()

# 모델 블록 조립
model.add(keras.layers.Input(shape=(x_train.shape[1],)))
model.add(keras.layers.Dense(128, 'swish'))
model.add(keras.layers.Dense(32, 'swish'))
model.add(keras.layers.Dense(y_train.shape[1], 'softmax'))

# 모델 컴파일
model.compile(loss = keras.losses.categorical_crossentropy, metrics= ['accuracy'],
              optimizer = 'adam')

# 모델 요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1792      
                                                                 
 dense_1 (Dense)             (None, 32)                4128      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 6,019
Trainable params: 6,019
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor = 'val_loss',
                   patience = 5,
                   min_delta = 0,
                   verbose = 1,
                   restore_best_weights = True)

In [ ]:
model.fit(x_train, y_train, verbose= 1, epochs=100,
          callbacks = [es], validation_split=0.2)

Epoch 1/100
4/4 [==============================] - 2s 85ms/step - loss: 1.0814 - accuracy: 0.4333 - val_loss: 1.0562 - val_accuracy: 0.4839
Epoch 2/100
4/4 [==============================] - 0s 15ms/step - loss: 1.0490 - accuracy: 0.4250 - val_loss: 1.0286 - val_accuracy: 0.3871
Epoch 3/100
4/4 [==============================] - 0s 14ms/step - loss: 1.0172 - accuracy: 0.4583 - val_loss: 0.9972 - val_accuracy: 0.6452
Epoch 4/100
4/4 [==============================] - 0s 20ms/step - loss: 0.9884 - accuracy: 0.6000 - val_loss: 0.9638 - val_accuracy: 0.7097
Epoch 5/100
4/4 [==============================] - 0s 20ms/step - loss: 0.9574 - accuracy: 0.7333 - val_loss: 0.9319 - val_accuracy: 0.8065
Epoch 6/100
4/4 [==============================] - 0s 20ms/step - loss: 0.9264 - accuracy: 0.8750 - val_loss: 0.8996 - val_accuracy: 0.8387
Epoch 7/100
4/4 [==============================] - 0s 20ms/step - loss: 0.8908 - accuracy: 0.9083 - val_loss: 0.8627 - val_accuracy: 0.8710
Epoch 8/100
4/4 [===

In [ ]:
print(model.evaluate(x_train, y_train))
print(model.evaluate(x_test, y_test))

5/5 [==============================] - 0s 5ms/step - loss: 0.0139 - accuracy: 1.0000
[0.013877900317311287, 1.0]
1/1 [==============================] - 0s 26ms/step - loss: 0.0382 - accuracy: 0.9630
[0.0382344052195549, 0.9629629850387573]


In [ ]:
print(y_test[:5])
print(model.predict(x_test)[:5])

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
1/1 [==============================] - 0s 18ms/step
[[1.3069384e-04 9.9986804e-01 1.3195097e-06]
 [1.2726094e-05 2.5211995e-05 9.9996209e-01]
 [3.0810248e-02 9.6918845e-01 1.2706397e-06]
 [1.5193306e-05 1.2371303e-04 9.9986112e-01]
 [8.9047245e-07 9.9999917e-01 1.8995619e-08]]
